# object_name is not being used right now (!)
object_name: '10' # Your object's name
mqtt_broker_ip: '192.168.1.77' # IP Address for mqtt broker
mqtt_topic: 'vehicle/11/status' # Topic name that you want to subscribe to