parking_patterns:
  "1":
    x_opt: 0.0
    y_opt: 8.5413
    target_april_tag: 30
    initial_rotation: "LEFT"
  "-1":
    x_opt: 0.0
    y_opt: 0.0
    target_april_tag: 239
    initial_rotation: "RIGHT"

optitrack_positional_threshold: 0.001
optitrack_angle_threshold: 0.001
april_tag_centering_threshold: 80
april_tag_check_position_x: 334
april_tag_check_position_y: 138
april_tag_area_of_covering_threshold: 0.6
april_tag_average_size_threshold: 20
april_tag_bounding_box_size : 150
speed_changing_threshold: 100

# Movement stack

move_speed:  1
rotation_speed:  0.5
move_speed_slow: 0.5
rotation_speed_slow: 0.3
move_time:  0.05
rotation_time: 0.05
move_time_slow:  0.05
rotation_time_slow: 0.05

sleep_after_move: 0.01