type_dict:
  #type of unknown apriltag is zero

  #type of "stop to think apriltag"
  "239": 1
  #type of "center of the parking lot apriltag"
  "30": 2

cent_x: 500
cent_y: 150
cent_x_d: 0
cent_y_d: 3
size: 67
size_d: 13
resize: 6
parking_trigger_apriltag: 533