type_dict:
  #type of unknown apriltag is zero

  #type of "stop to think apriltag"
  "239": 1
  #type of "center of the parking lot apriltag"
  "30": 2

cent_x: 480
cent_y: 150
cent_x_d: 70
cent_y_d: 100
size: 65
size_d: 30
resize: 6
parking_trigger_apriltag: 533
detection_latency: 1